gtest_web/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import InputRequired

class SubmitForm(FlaskForm):
    problem_id = StringField("Problem", validators=[InputRequired()])
    language = SelectField("Language", choices=[("python3", "python3")], validators=[InputRequired()])
    source_code = TextAreaField("Source Code", validators=[InputRequired()])

gtest_web/main/__init__.py
from .routes import main_blueprint

gtest_web/main/routes.py
import json
import uuid
import datetime

import boto3
import flask
import flask_login

from shared import data
from shared.problems import list_problem_ids
from gtest_web.main.forms import SubmitForm

main_blueprint = flask.Blueprint("main", __name__, template_folder="templates")

@main_blueprint.before_app_request
def load_dynamodb_tables():
    dynamodb = boto3.resource("dynamodb")
    flask.g.report_table = dynamodb.Table(flask.current_app.config["REPORT_TABLE_NAME"])

@main_blueprint.route("/", methods=("GET",))
def index():
    index_url = flask.url_for(flask.current_app.config["INDEX_VIEW"])
    return flask.redirect(index_url)

@main_blueprint.route("/problems", methods=("GET",))
@flask_login.login_required
def problems():
    problem_ids = list_problem_ids(flask.current_app.config["PROBLEM_BUCKET"])
    return flask.render_template("main/problems.html", problem_ids=problem_ids)

@main_blueprint.route("/submit/<problem_id>", methods=("GET", "POST"))
@flask_login.login_required
def submit(problem_id):
    form = SubmitForm()
    form.problem_id.data = problem_id
    if form.validate_on_submit():
        solution_id=str(uuid.uuid4())
        solution = data.Solution(
            solution_id=solution_id,
            problem_id=form.problem_id.data,
            user_id=flask_login.current_user.user_id,
            submitted=datetime.datetime.now(),
            language=form.language.data,
            source_code=form.source_code.data)
        solution_item = data.SolutionSchema().dump(solution)
        queue = boto3.resource("sqs").Queue(flask.current_app.config["SOLUTION_QUEUE_URL"])
        queue.send_message(
            MessageBody=json.dumps(solution_item),
            MessageGroupId="solution",
            MessageDeduplicationId=solution_id)
        return flask.redirect(flask.url_for("main.reports"))
    return flask.render_template("main/submit.html", form=form)

@main_blueprint.route("/reports/<solution_id>", methods=("GET",))
@flask_login.login_required
def report(solution_id):
    response = flask.g.report_table.get_item(Key={"solution_id": solution_id})
    if report_item := response.get("Item"):
        _report = data.ReportSchema().load(report_item)
        if _report.user_id != flask_login.current_user.user_id:
            flask.abort(400)
        return flask.render_template("main/report.html", report=_report)
    return flask.abort(404)

@main_blueprint.route("/reports", methods=("GET",))
@flask_login.login_required
def reports():
    user_id = flask_login.current_user.user_id
    params = {
        "Limit": 20,
        "IndexName": "user_id-index",
        "KeyConditionExpression":  boto3.dynamodb.conditions.Key("user_id").eq(user_id)
    }
    response = flask.g.report_table.query(**params)
    items = response.get("Items") or []
    _reports = [data.ReportSchema().load(i) for i in items]
    return flask.render_template("main/reports.html", reports=_reports)

gtest_web/main/templates/main/problems.html
{% extends "base.html" %}

{% block content %}
<div class="box">
  <h1 class="title">Problems</h1>
  <table class="table">
    <thead>
    <tr>
      <th>Id</th>
      <th>Submit</th>
    </tr>
    </thead>
    <tfoot>
      {% for id in problem_ids %}
      <tr>
        <td>{{ id }}</td>
        <td><a href="{{ url_for('main.submit', problem_id=id) }}">Submit</a></td>
      </tr>
      {% endfor %}
    </tfoot>
  </table>
</div>
{% endblock %}

gtest_web/main/templates/main/report.html
{% extends "base.html" %}

{% block content %}
<div class="box">
    <h1 class="title">Solution Report</h1>
    <table>
      <tfoot>
        <tr>
          <td>Solution</td>
          <td>{{ report.solution_id }}</td>
        </tr>
        <tr>
          <td>Problem</td>
          <td><a href="{{ url_for('main.submit', problem_id=report.problem_id) }}">{{ report.problem_id }}</a></td>
        </tr>
        <tr>
          <td>Tests overall</td>
          <td>{{ report.tests_overall }}</td>
        </tr>
        <tr>
          <td>Tests passed</td>
          <td>{{ report.tests_passed }}</td>
        </tr>
      </tfoot>
    </table>
</div>
{% endblock %}

gtest_web/main/templates/main/reports.html
{% extends "base.html" %}

{% block content %}
<div class="box">
  <h1 class="title">Reports</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Solution</th>
        <th>Submitted</th>
        <th>Problem</th>
        <th>Status</th>
      </tr>
    </thead>
    <tfoot>
      {% for report in reports %}
      {% set ok = report.tests_overall == report.tests_passed %}
      {% set wa = not ok %}
      <tr>
        <td><a href="{{ url_for('main.report', solution_id=report.solution_id) }}">{{ report.solution_id }}</a></td>
        <td>{{ report.submitted.strftime("%Y-%m-%d %H:%m") }}</td>
        <td><a href="{{ url_for('main.submit', problem_id=report.problem_id) }}">{{ report.problem_id }}</a></td>
        <td style="background-color: 
                    {% if ok %} 
                      hsl(141, 53%, 53%)
                    {% elif wa %}
                      hsl(348, 100%, 61%)
                    {% endif %}">
          {% if ok %}
            Success
          {% elif wa %}
            Wrong Answer
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tfoot>
  </table>
</div>
{% endblock %}

gtest_web/main/templates/main/submit.html
{% extends "base.html" %}

{% block content %}
<div class="column is-half is-offset-one-quarter">
  <div class="box">
    <h1 class="title">Submit</h1>
    <form method="POST" action="{{ url_for('main.submit', problem_id=form.problem_id.data) }}">
      {{ form.csrf_token }}
      <div class="field">
        {{ form.problem_id.label(class="label") }}
        <div class="control">
          {{ form.problem_id(class="input") }}
        </div>
      </div>
      <div class="field">
        {{ form.language.label(class="label") }}
        <div class="control">
          <div class="select">
            {{ form.language }}
          </div>
        </div>
      </div>
      <div class="field">
        {{ form.source_code.label(class="label") }}
        <div class="control">
          {{ form.source_code(class="textarea", rows="20", cols="50") }}
        </div>
      </div>
      <div class="field">
        <input class="button is-primary" type="Submit" value="Submit">
      </div>
    </form>
  </div>
</div>
{% endblock %}